### ISSUE TITLE
Is there a matlab version?

### ISSUE THREAD

**Issue by TangLaoya** [pradovera/greedy-loewner#1]
The algorithm seems perfect, is there a matlab version?

Thanks,

Tang Laoya

**Comment by pradovera** [comment]
This repo only contains code for reproducibility purposes.
I'm planning to publish a (more) proper library in a separate repo soon. I'll link it here as soon as it's ready.
At the moment, I don't have a MATLAB version of the algorithm but, if there is interest, I'll port my code to MATLAB too.
Davide

**Comment by TangLaoya** [comment]
Dear Davide,
Thank you very much for your kindly reply. 
If you could provide the MATLAB version code, I would be extremely grateful.

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Furthermore, I have an initial sampling (3 curves of S parameters):
f=[1, 491000000, 1650000000, 4045000000, 8930000000, 17870000000, 32320000000, 53120000000, 76480000000, 100000000000];
and
S(f,1)=[0.00018299495402418486-i*0.00012853669220563120, 0.99981380772473694-i*0.00012853688505757958, 0.00018299476322658492-i*0.00012854565969819265, -0.0079241556293371262-i*0.017490907824259303, 0.95391526440148111-i*0.26976536529283296, -0.0079414856722879179-i*0.017485347858662872, -0.058364386855537465-i*0.034325076191775029, 0.58989424039502503-i*0.77111160381571064, -0.058379491488655733-i*0.034239992001417911, -0.091585260334134500+i*0.082054803791689321];

S(f,2)=[-0.58412183598534351-i*0.73702311462368453, -0.091418112097978454+i*0.082264634317711582, -0.087927691450689904+i*0.049922019198327380, 0.19326777465314290+i*0.86377706904702045, -0.087666348913242875+i*0.050273439646599430, 0.080109529128773005+i*0.22327776567011792, -0.71280345302317893+i*0.29721540543544978, 0.080086178333470093+i*0.22356670474323670, 0.046987798294753302+i*0.11808144506259330, 0.18659249397191954+i*0.60092057255288944];

S(f,3)=[0.048447872142741488+i*0.12039041964013455, 0.21603700029078143+i*0.30647627646332570, -0.42266542974067040+i*0.019265102830542599, 0.23074706290117875+i*0.29545186063123691, 0.44377538385778226+i*0.044731103064397766, -0.057571334488274742-i*0.29149711355698016, 0.43668432734136409+i*0.057441221309918522, 0.38525900630544752-i*0.070578616405603298, 0.21914358970086056+i*0.059112478938450314, 0.41209622936113566-i*0.050238437121664543];

How to generate the next group of samplings by this greedy sampling code? 

I noticed that you mention the AAA algorithm for rational approximation, and it also calculated the poles and zeros of current approximation, what's the relationship of next group of samplings and the poles/zeros?

Thanks,
Tang Laoya

**Comment by pradovera** [comment]
A library containing the greedy-Loewner method is now available [here](https://github.com/pradovera/gLoewner). Both Python and MATLAB versions of the code are provided.

Now to your latest questions. In v1.1 of `gLoewner`, it is possible to manually specify the initial training set. In your case, I would
* define a `sampler` function (e.g., an anonymous function in MATLAB) that, given a single frequency, returns the corresponding S-parameters as a vector (e.g., `sampler = @(z) [1/(z+1); -2/z; 3*z/(z+1)];`);
* initialize an array, named `z_test`, with many elements (say, 10^5) between `1` and `100000000000`, _including your initial sampled frequencies `f`_ (this is important);
* define an array of integers, named `start_z_idx`, as the set of indices that `f` occupy within `z_test`.

Those will be the first three arguments of the function `trainSurrogate` in `gLoewner`. Then you just have to choose an estimator among those available (as described in [here](https://doi.org/10.1007/s10444-023-10091-7)).

About computing poles and zeros, at the moment the functionality is absent from `gLoewner`. I might add it in the future. However, once you have the barycentric coefficients of a rational function, it's easy to find its roots and poles. See, e.g., how it's done in the [AAA algorithm](https://doi.org/10.1137/16M1106122) as implemented in [Chebfun](https://www.chebfun.org/).

Each new sample point will change the barycentric coefficients and, in turn, the poles and zeros in unpredictable ways. After all, we're talking about rational approximation (even worse, of rational _interpolation_!), which is notoriously not robust...

Davide

**Comment by TangLaoya** [comment]
Thank you very much!
